### ISSUE TITLE
Health Bug

### ISSUE THREAD

**Issue by N4tiM** [Vladislav2437/EnhancedCustomRoles#11]
![image](https://github.com/Vladislav2437/EnhancedCustomRoles/assets/80088980/57e48b77-d62a-47ce-a118-f41f1dc62b19)
If you set hp, it does not become maximum. For example: if you put 150 hp, you can not regenerate back to 150, or if you put 50 hp, you can regenerate back to 100

**Comment by Vladislav2437** [comment]
fixed in the last release
