### ISSUE TITLE
GiveRole sometimes doesn't give the role (possibly to players with one-digit IDs

### ISSUE THREAD

**Issue by Skubers** [Vladislav2437/EnhancedCustomRoles#12]
![image](https://github.com/Vladislav2437/EnhancedCustomRoles/assets/82095491/271bc8a3-db7b-42c9-8f55-6d3be24d85ca)

**Comment by Vladislav2437** [comment]
It's not actually a problem of my plugin, but it seems like an exiled plugin, it works after you use in RA kill [id] and then try to give the role to that id
