### ISSUE TITLE
"Concussed" status effect doesn't apply if given to a Human role as a Damage Effect

### ISSUE THREAD

**Issue by Skubers** [Vladislav2437/EnhancedCustomRoles#7]
1. Give a human (ClassD, Scientist, MTF, Guard, CI) a customRole with "Concussed" damage effect
2. Give them a Jailbird or anything else damaging
3. Observe as the enemy doesn't get concussed upon hit

**Comment by Vladislav2437** [comment]
Fixed DamageEffect property(i forgot to add the feature lol but now it's working correctly)
